apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maftei/k8s.git
    targetRevision: HEAD
    path: crud/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: crud-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
